 server.modules += ( "mod_deflate" )

 deflate.mimetypes = ("text/html", "text/plain", "text/css", "text/javascript")
 deflate.allowed-encodings = ("gzip", "deflate")
 deflate.max-compress-size = 131072
 deflate.min-compress-size = 512
 deflate.max-loadavg = "3.0"
