theme: jekyll-theme-cayman

title: KickStartTrustee
description: Ein branchenübergreifender Leitfaden für die zielgerichtete Konzeption, die beschleunigte Umsetzung und den erfolgreichen Betrieb von Datentreuhändern 
use_breadcrumbs: true
locale: de_DE

plugins:
  - jemoji
  - jekyll-seo-tag
